import { Nunito_Sans } from "next/font/google";
import "./globals.css";
const nunito_Sans = Nunito_Sans({ weight: ["400"], subsets: ["cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_Sans.className}>{children}</body>
    </html>
  );
}
